### ISSUE TITLE
Remove users having <20% match from results page

### ISSUE THREAD

**Issue by akhilchoudhary2k** [akhilchoudhary2k/MindMatch-kgp#15]
Outcome: We don't want users having <20% match to be included in the results page

Testing web-page: https://mindmatchkgp.herokuapp.com/getsuggestions
Function to be modified: [LINK](https://github.com/akhilchoudhary2k/MindMatch-kgp/blob/master/app.js#L499)

**Comment by rohitsinghind** [comment]
can u assign this to me

**Comment by akhilchoudhary2k** [comment]
@rohitsinghind assigning this to you.

**Comment by AnjaliChoudhary99** [comment]
@akhilchoudhary2k  hi, can you assign it to me, as there is no progress since many days.

**Comment by akhilchoudhary2k** [comment]
@AnjaliChoudhary99 ,Done.

@rohitsinghind pls continue with https://github.com/akhilchoudhary2k/MindMatch-kgp/issues/11

**Comment by AnjaliChoudhary99** [comment]
@akhilchoudhary2k  changes done, review my PR https://github.com/akhilchoudhary2k/MindMatch-kgp/pull/30
