### ISSUE TITLE
Add validation check to all fields in register page

### ISSUE THREAD

**Issue by akhilchoudhary2k** [akhilchoudhary2k/MindMatch-kgp#23]
Testing web-page: https://mindmatchkgp.herokuapp.com/register

Required validations:
-- no space in username field
-- atleast 4 characters in username
-- any other validations are welcome

**Comment by pstreemaze** [comment]
Please assign this to me

**Comment by ritiksp2411** [comment]
please assign this to me

**Comment by akhilchoudhary2k** [comment]
@ritiksp2411 assigned to you, post here if you have any doubts.
