### ISSUE TITLE
Put error message when wrong credentials are entered.

### ISSUE THREAD

**Issue by akhilchoudhary2k** [akhilchoudhary2k/MindMatch-kgp#33]
Instead of the text "Unauthorized", print a proper error message.

**Comment by rehanmm** [comment]
can you please assign this to me?

**Comment by akhilchoudhary2k** [comment]
@rehanmm  Okay but try to close this in a day or so, as it is an easy issue.

**Comment by nghiab1910673** [comment]
Can you assign this to me, please? I feel interesting in this problem.

**Comment by akhilchoudhary2k** [comment]
Hey @nghiab1910673 thanks for showing interest.
But this issue has already been resolved and closed.
