### ISSUE TITLE
Do not show admin profile in search results

### ISSUE THREAD

**Issue by akhilchoudhary2k** [akhilchoudhary2k/MindMatch-kgp#35]
**Steps**: when we push a user into the results list, just put a check that it's not `admin`

Refer to this image.
<img width="751" alt="Screenshot 2022-10-27 at 2 02 41 AM" src="https://user-images.githubusercontent.com/42896296/198131653-e2902ed4-5324-49ff-8dee-7339383d9c9e.png">

**Comment by Ishikasaraf20** [comment]
hey @akhilchoudhary2k can you assign thiis issue to me i can work on it

**Comment by akhilchoudhary2k** [comment]
It mostly requires changes somewhere near this line: [LINK](https://github.com/akhilchoudhary2k/MindMatch-kgp/blob/master/app.js#L547)

@Ishikasaraf20 try to raise the PR as soon as possible.

**Comment by akhilchoudhary2k** [comment]
@Ishikasaraf20 Need any help? Close this task ASAP

**Comment by AnjaliChoudhary99** [comment]
@akhilchoudhary2k  hi, can you assign it to me

**Comment by rehanmm** [comment]
@akhilchoudhary2k  i have fixed it
