### ISSUE TITLE
Make username field case in-sensitive

### ISSUE THREAD

**Issue by akhilchoudhary2k** [akhilchoudhary2k/MindMatch-kgp#38]
Before using `username` convert all alphabets in it to lowercase.
In `POST: /login` and `POST: /register` route: 
do something like `username = lowerCase(req.body.username)` and then use it in the further lines

e.g. XYZ123 should be saved as xyz123

NOTE: apply it for registering new user, **also** for logging in the existing users.

**Comment by singhkaran202** [comment]
Hello @akhilchoudhary2k, I'd love to work on this.
Can you please assign this to me?

**Comment by akhilchoudhary2k** [comment]
@singhkaran202 assigning it to you, but try to resolve it ASAP. Otherwise might have to reassign as it's a simple task.
And reach out to me if you need any help

**Comment by akhilchoudhary2k** [comment]
@singhkaran202 assigning it to you, but try to resolve it ASAP. Otherwise might have to reassign as it's a simple task.
And reach out to me if you need any help

**Comment by akhilchoudhary2k** [comment]
And before raising PR, make sure to test on a few examples like
xyz --> xyz
XYZ --> xyz
Xyz --> xyz
Xyz@123 -->xyz@123
!@#123 -->!@#123
and other combinations

**Comment by singhkaran202** [comment]
Yeah sure, I'll resolve it super soon!!
Thanks for assigning @akhilchoudhary2k !!

**Comment by singhkaran202** [comment]
@akhilchoudhary2k, I think I'll need a .env file because I am not able to run it in my local machine, I am getting errors regarding it.
Really sorry if I'm wrong, please guide me little, I promise I'll complete it very soon

Error I'm getting is attached herewith:

![error ss](https://user-images.githubusercontent.com/105576642/198260674-fad0c957-6783-4070-855b-be5d6ca403a1.png)

**Comment by akhilchoudhary2k** [comment]
Did you follow the readme file to correctly run the code locally ??
bcz when you set the `locally_running = true`, it will not take the `env` variables.

**Comment by singhkaran202** [comment]
Ohh sorry, I missed changing the value to true.
Now, its running locally fine

**Comment by akhilchoudhary2k** [comment]
@singhkaran202 Need any help? Close this task ASAP

**Comment by akhilchoudhary2k** [comment]
@singhkaran202 I've update the details, have a look and close it quickly.

**Comment by rehanmm** [comment]
can you assign this to me

**Comment by akhilchoudhary2k** [comment]
@rehanmm pls raise the PR

**Comment by akhilchoudhary2k** [comment]
@rehanmm I left this comment: https://github.com/akhilchoudhary2k/MindMatch-kgp/pull/43#issuecomment-1295791844
