### ISSUE TITLE
Update text on login page

### ISSUE THREAD

**Issue by akhilchoudhary2k** [akhilchoudhary2k/MindMatch-kgp#42]
Replace `(not e-mail ID)` with `(case in-sensitive)`

<img width="550" alt="Screenshot 2022-10-29 at 1 38 58 AM" src="https://user-images.githubusercontent.com/42896296/198723346-edfb029c-f5a9-497f-a5a2-9194ac3ffeac.png">

**Comment by rehanmm** [comment]
plz assign this to me?

**Comment by rehanmm** [comment]
assign this to me
